def process_event(event, keyboard):
    if keyboard == "qwerty":
        if event.keysym == "BackSpace":
            return -1
        elif event.keysym == "Return":
            return "\n"
        elif len(event.char) == 1:
            return event.char
    elif keyboard == "dvorak":
        if event.keysym == "BackSpace":
            return -1
        elif event.keysym == "Return":
            return "\n"
        elif len(event.char) == 1:
            return dvorak_converted(event.char)
        
def dvorak_converted(char):
    match char:
        # Lowercase letters
        case "a":
            return "a"
        case "n":
            return "b"
        case "i":
            return "c"
        case "h":
            return "d"
        case "d":
            return "e"
        case "y":
            return "f"
        case "u":
            return "g"
        case "j":
            return "h"
        case "g":
            return "i"
        case "c":
            return "j"
        case "v":
            return "k"
        case "p":
            return "l"
        case "m":
            return "m"
        case "l":
            return "n"
        case "s":
            return "o"
        case "r":
            return "p"
        case "x":
            return "q"
        case "o":
            return "r"
        case ";":
            return "s"
        case "k":
            return "t"
        case "f":
            return "u"
        case ".":
            return "v"
        case ",":
            return "w"
        case "b":
            return "x"
        case "t":
            return "y"
        case "/":
            return "z"
        # Capital letters
        case "A":
            return "A"
        case "N":
            return "B"
        case "I":
            return "C"
        case "H":
            return "D"
        case "D":
            return "E"
        case "Y":
            return "F"
        case "U":
            return "G"
        case "J":
            return "H"
        case "G":
            return "I"
        case "C":
            return "J"
        case "V":
            return "K"
        case "P":
            return "L"
        case "M":
            return "M"
        case "L":
            return "N"
        case "S":
            return "O"
        case "R":
            return "P"
        case "X":
            return "Q"
        case "O":
            return "R"
        case ":":
            return "S"
        case "K":
            return "T"
        case "F":
            return "U"
        case ">":
            return "V"
        case "<":
            return "W"
        case "B":
            return "X"
        case "T":
            return "Y"
        case "?":
            return "Z"
        # Symbols
        case "e":
            return "."
        case "E":
            return ">"
        case "w":
            return ","
        case "W":
            return "<"
        case "q":
            return "'"
        case "Q":
            return '"'
        case "[":
            return "/"
        case "{":
            return "?"
        case "]":
            return "="
        case "}":
            return "+"
        case "'":
            return "-"
        case '"':
            return "_"
        case "-":
            return "["
        case "_":
            return "{"
        case "=":
            return "]"
        case "+":
            return "}"
        case "z":
            return ";"
        case "Z":
            return ":"
        case _:
            return char
        